/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Berachef } from "./Berachef";
export type { Bgt } from "./Bgt";
export * as factories from "./factories";
export { Berachef__factory } from "./factories/Berachef__factory";
export { Bgt__factory } from "./factories/Bgt__factory";
